name: paymentez
description: Paymentez SDK for Ecuador.
version: 0.5.1
author: Jean Roldan at Paymentez
homepage: https://www.paymentez.com.ec/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  crypto: ^3.0.1
  dart_ipify: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:

flutter:
